STELLAR_URL = 'https://test.stellar.org:9002'
STELLAR_WS = 'ws://test.stellar.org:9001'
SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:your-password@localhost/stellarrobot'
STELLAR_ADDRESS = 'your-stellar-address'
STELLAR_SECRET_KEY = 'your-stellar-secret-key'
